import type { Metadata } from "next";
import Navbar from '@/components/Navbar';

// INIT
import "@/styles/reset/reset.scss";
import "@/styles/init.scss";
import '@/styles/comp-aside-profile.scss';
import '@/styles/layout-models.scss';
import '@/styles/layout-navbar.scss';
import '@/styles/comp-news.scss';
import '@/styles/comp-avatar.scss';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <div id='layout'>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}




